### ISSUE TITLE
Is this licensed?

### ISSUE THREAD

**Issue by tadhisoy** [mprahl/ADReset#15]
I am interested in this application and would like to use it, but since there is no license display, I am not sure whether to modify it or not.

Is it possible to get an MIT license etc.?

thanks.

**Comment by mprahl** [comment]
Hi @tadhisoy, I added a GPL license at https://github.com/mprahl/ADReset/commit/e52f8306a490d7e981be4b3e7860acaf47bb06d1.

Please note that I'm currently working on a modern rewrite at https://github.com/mprahl/ADReset2, which includes a REST API and a UI written in React. If you'd like to help, that'd be greatly appreciated. It's currently on hold until December though since I'm busy until then.

**Comment by tadhisoy** [comment]
Thank you for your quick response. I'm looking forward to ADReset2 too.
